### ISSUE TITLE
OC Meeting Agenda 2023-02-07

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/oc#10]
Time 5pm (GMT) - See the time in your [timezone](https://everytimezone.com/s/99162c8e)

- Chair – Tammy McClellan @tmcclell (Microsoft)  
- Vice-Chair – Chris Lloyd-Jones @Sealjay (Avanade)
- Convener – Sean Mcilroy @seanmcilroy29  (GSF)

## Roll Call
Please add 'Attended' to this issue during the meeting to denote attendance.
Any untracked attendees will be added by the GSF team below:

## Agenda
- [x] Welcome our new Chair and Vice-Chair.
- [x] Asim: Discuss repository clean-up project including renaming, permissioning, proposed deletions and mandatory meta information to be added to every repo's readme. https://github.com/Green-Software-Foundation/ops-admin/issues/146
- [x] Asim: Discuss project proposal template as per https://github.com/Green-Software-Foundation/oc/discussions/7
- [x] Asim: Discuss change to have 3 co-chairs instead of 2 as per https://github.com/Green-Software-Foundation/oc/discussions/9
- [x] Asim: Discuss PM hiring process.
- [x] Asim: Discuss elections
- [ ] Asim: OKR Tracking.
- [ ] Sean: Budget Tracking.
- [ ] CLJ: https://github.com/Green-Software-Foundation/oc/discussions/11

## Decisions 
- [x] Asim: Motion to increase the time for this meeting to 1 hr to cover all the agenda items starting at 0900-1000 am PT / 1700 pm to 1800 pm UTC.

## Actions
- [ ] @jawache: For the next meeting create package of changes to show how to update the charter for the 3 chairs.
- [ ] @jawache: Change next meeting to 1hr long starting at 4:30 GMT

**Comment by tmcclell** [comment]
Attended

**Comment by Sealjay** [comment]
Attended! Woohoo!

**Comment by greenhsu123** [comment]
attended :)

**Comment by Henry-WattTime** [comment]
Attended, good banter this meeting

**Comment by atg-abhishek** [comment]
Attended

**Comment by atg-abhishek** [comment]
> Attended, good banter this meeting

Memorialized in the recording lol

**Comment by seanmcilroy29** [comment]
attended

**Comment by jawache** [comment]
Agree to change meeting to 1hr 4:30pm to 5:30 pm GMT

**Comment by seanmcilroy29** [comment]
Agreed
