### ISSUE TITLE
OC Meeting Agenda 2023-03-07

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/oc#14]
Time 5pm (GMT) - See the time in your [timezone](https://everytimezone.com/s/99162c8e)

- Chair – Tammy McClellan @tmcclell (Microsoft)  
- Vice-Chair – Chris Lloyd-Jones @Sealjay (Avanade)
- Convener – Sean Mcilroy @seanmcilroy29  (GSF)

## Antitrust Policy
Joint Development Foundation meetings may involve participation by industry competitors, and it is the intention of the Joint Development Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

If you have questions about these matters, please contact your company counsel or counsel to the Joint Development Foundation, DLA Piper.

## Roll Call
Please add 'Attended' to this issue during the meeting to denote attendance.
Any untracked attendees will be added by the GSF team below:

## Agenda
- [x] Review/Approve agenda

## Agenda
- [x] Sean: Budget Tracking.
- [x] CLJ @Sealjay: An update on member onboarding - https://github.com/Green-Software-Foundation/oc/discussions/11
- [x] Sarah @greenhsu123: Sustainable API Green Score - How should we engage with higher education?  - https://github.com/Green-Software-Foundation/oc/discussions/16
- [x] Sarah @greenhsu123: https://github.com/Green-Software-Foundation/oc/discussions/17
- [ ] CLJ @Sealjay / @tmcclell in CLJ's absence: Making sure the OC knows the impact of DCO[^1] for their working group https://github.com/Green-Software-Foundation/discussions/discussions/5
- [ ]  Tammy @tmcclell : Answering the so what. https://github.com/Green-Software-Foundation/oc/discussions/18
- [ ] Asim: OKR Tracking.

## Updates
- [ ] CarbonQL: https://github.com/Green-Software-Foundation/carbon-ql
- [ ] Meetup: https://github.com/Green-Software-Foundation/meetup

## Pull-request
- [ ] @jawache Updates to the charter

## Actions
- [ ]: **All working group chairs/project leads**: Ensure their team members [are aware of the impact of DCO](https://github.com/Green-Software-Foundation/discussions/discussions/5) (commits should be signed with `-s`[^2])

[^1]: https://developercertificate.org/
[^2]: https://github.com/dcoapp/app#how-it-works

**Comment by Willmish** [comment]
HI @jawache - wanted to double check what time the meeting is at - I have invites for both 4:30pm -5:30pm GMT and 5:30pm to 6:00pm GMT. Which one is the correct one?

**Comment by seanmcilroy29** [comment]
Hi @Willmish - The meeting schedule was updated to last 1 hr and to start slightly earlier at 4:30 pm --> 5:30 pm

**Comment by tmcclell** [comment]
Attended

**Comment by Willmish** [comment]
Attended

**Comment by dtoakley-tw** [comment]
Attended

**Comment by atg-abhishek** [comment]
Attended

**Comment by Henry-WattTime** [comment]
attended (second half)
