### ISSUE TITLE
[Agenda Item] Audit our current 'graduated' projects

### ISSUE THREAD

**Issue by Sealjay** [Green-Software-Foundation/oc#23]
**Overview**:
> Current projects don't actually meet our current criteria of [graduated](https://oc.greensoftware.foundation/project-incubation-exit.html). Let's discuss which projects we "think" are graduated, and then assign someone to do an audit to see what's missing.

**Related topic**: The type of agenda item you want to propose.
- [ ] Governance: New project
- [x] Governance: Other
- [x] Process
- [ ] External Engagement
- [ ] Technology
- [ ] Other

**Related working groups**:

- [x] Community
- [x] Open Source
- [ ] Policy
- [x] Standards

**Related issues or discussions**:

n/a

**Comment by Sealjay** [comment]
@jawache  moved from email

**Comment by tmcclell** [comment]
Graduated (released versions, mature enough to be useful) projects - SCI, Carbon Aware SDK, Principles Training (Certificate of Completion), Patterns v1, Awesome Green Software. Incubation definition - Alpha version. Proposed that Oleg will come back with a list of criteria for graduated (released). Approved by OC

**Comment by Sealjay** [comment]
Adding the guidelines:
https://oc.greensoftware.foundation/project-incubation-exit.html

**Comment by tmcclell** [comment]
Discussion around Project Incubation Exit criteria. Proposal is to create a Issue template with exit criteria checklist - flag issues for exceptions or change in criteria. @Oleg-Zhymolokhov to create issues around exiting graduated projects for feedback. Process to come out through digest for overall feedback. @jawache - ideas for celebration on graduation - possible swag. Keep on agenda for next month.

**Comment by Willmish** [comment]
For celebrating incubated projects - suggested swag or release parties (similar to how we ran workshops during the CarbonHack for CA SDK)? @danuw I remember you mentioning holding one for the CA SDK, maybe we could make that a thing after all

**Comment by tmcclell** [comment]
@Oleg-Zhymolokhov to create issues around exiting graduated projects for feedback. Process to come out through digest for overall feedback.

**Comment by jawache** [comment]
Hey @tmcclell / @seanmcilroy29 and @Sealjay - this should be the top priority of the OC. We've got currently 0 graduated projects and yet we treat some projects differently than others. That's unfair.

This group has to come up with the process, can we put this to the top of the agenda and make it number one on an ongoing basis?

**Comment by russelltrow** [comment]
Doing a little research I came across a concise set of 'adoption' requirements from the Academy Software Foundation (ASWF):

```Adopted Stage projects are considered mature projects that generally are ready for production use. Projects at this stage focus on growing an ecosystem of users and are often being leveraged in vendor products or used by end-users.```

- Demonstrate a substantial ongoing flow of commits and merged contributions authored by a healthy number of diverse contributors*.
- Demonstrable roadmap progress.
- A significant number of end-users [...]that have adopted the project and that are identified within the project (using an ADOPTERS file or showcased on the project’s website).
- Have achieved and maintained an OpenSSF Best Practices Badge at the [gold level].
- Have a technical lead appointed for voting representation of the project to the TAC.
- Be deemed by the TAC to add value to the mission of the Academy Software Foundation.

https://tac.aswf.io/process/lifecycle#requirements-2

**Comment by russelltrow** [comment]
I've moved the existing exit criteria to Confluence so we can more easy collaborate on them: https://greensoftwarefoundation.atlassian.net/wiki/spaces/~612dd45e45cd76006a84071a/pages/72941569/Incubation+Exit+Criteria

**Comment by Sophietn** [comment]
Graduation Acceptance criteria (renaming of Incubation exit criteria) has been updated. This was approved by the OC async via email, and added to the OC website through an update to the whole 'Software' [Project Lifecycle](https://oc.greensoftware.foundation/project-lifecycle.html) via this pull request #64 
Updates to 'Document' Project Lifecycle to follow. 
Lifecycle stage is being discussed at GSF PM <> PL level, and mature projects are working towards fulfilling the new criteria, and achieving the 'Graduated' Lifecycle Stage. OC will be notified to review, once projects are ready.
