### ISSUE TITLE
[Agenda Item] Criteria for donating or accepting projects into GSF from outside GSF

### ISSUE THREAD

**Issue by Sealjay** [Green-Software-Foundation/oc#25]
**Overview**:
> Agree if we want to accept non-GSF projects into the GSF, and if so, what are the criteria for donating a project to the GSF

**Related topic**: The type of agenda item you want to propose.
- [ ] Governance: New project
- [x] Governance: Other
- [ ] Process
- [ ] External Engagement
- [ ] Technology
- [ ] Other

**Related working groups**:

- [ ] Community
- [ ] Open Source
- [ ] Policy
- [ ] Standards
- [ ] Oversight Committee

**Related issues or discussions**:
- https://github.com/Green-Software-Foundation/oc/discussions/22
- https://github.com/Green-Software-Foundation/opensource-wg/discussions/67#discussioncomment-5395663

**More information**:
> We may need to defer this until members have had time to discuss.

**Comment by tmcclell** [comment]
Henry proposed donated projects go through the same defined process for new projects. The donator either needs to give up lead or be a member of GSF and come under GSF governance. Guidelines for donating projects to be created- Asim will create a PR for OC review. - OC approved.

**Comment by Sophietn** [comment]
I have drafted a new Donation process, and gained internal approval. 
Review requested for PRs #70 and #71 
Notification and Motion raised to OC via email on Monday 18th December.
Feedback, comments, objections welcome. 
If no objections received after 5 days, Motion will be passed as agreed, and PRs will be merged on Friday 22nd December.

**Comment by Sophietn** [comment]
These PRs were merged after the donation process was approved. This is [visible on the OC website ](https://oc.greensoftware.foundation/project-donations.html)
