### ISSUE TITLE
[Agenda Item] Updates to the charter

### ISSUE THREAD

**Issue by Sealjay** [Green-Software-Foundation/oc#26]
**Overview**:
> @jawache to discuss updates to the OC charter.

**Related topic**: The type of agenda item you want to propose.
- [ ] Governance: New project
- [x] Governance: Other
- [ ] Process
- [ ] External Engagement
- [ ] Technology
- [ ] Other

**Related working groups**:

- [ ] Community
- [ ] Open Source
- [ ] Policy
- [ ] Standards
- [x]Oversight Committee

**Comment by tmcclell** [comment]
What are your proposal for updates to the charter?

**Comment by jawache** [comment]
I have a vague memory that I was supposed to change the charter to add information regarding 3 co-chairs for working groups.
