### ISSUE TITLE
[Agenda Item] Working group elections

### ISSUE THREAD

**Issue by Sealjay** [Green-Software-Foundation/oc#27]
**Overview**:
> Updates on election process and timelines.

**Related topic**: The type of agenda item you want to propose.
- [ ] Governance: New project
- [x] Governance: Other
- [x] Process
- [ ] External Engagement
- [ ] Technology
- [ ] Other

**Related working groups**:

- [x] Community
- [x] Open Source
- [x] Policy
- [x] Standards
- [x] Oversight Committee

**More information**:
> Updates on election process and timelines.

**Comment by tmcclell** [comment]
Motion to have elections in the fall - end of September, 2023. Transition periods until January 1st. New OC/WG Leads begin January 1. Also 2 year chair positions were proposed. No objections - OC approved.

**Comment by seanmcilroy29** [comment]
See #50
