### ISSUE TITLE
[Agenda Item] Request for SCI-Ontology Python developer

### ISSUE THREAD

**Issue by Sealjay** [Green-Software-Foundation/oc#28]
**Overview**:
> @navveenb of SCI-Ontology has requested a Python Developer for some time; what are the next steps.

**Related topic**: The type of agenda item you want to propose.
- [ ] Governance: New project
- [ ] Governance: Other
- [x] Process
- [ ] External Engagement
- [x] Technology
- [ ] Other

**Related working groups**:

- [ ] Community
- [x] Open Source
- [ ] Policy
- [ ] Standards
- [ ] Oversight Committee

**Related issues or discussions**:

https://github.com/Green-Software-Foundation/opensource-wg/issues/71

**Comment by tmcclell** [comment]
Proposed of assigning $10,000 to sci ontology project? No objections - OC approved.
