### ISSUE TITLE
[Agenda Item] Proposal for co-chair for carbonQL project

### ISSUE THREAD

**Issue by srini1978** [Green-Software-Foundation/oc#30]
**Overview**:
Wanted to open up the idea about having co-chair for Carbon QL project. I think Naveen Balani will be a great colleague as a co-chair as he comes with vast experience and we have been working closely on the SCI open data project which is closely aligned with this one.

**Related topic**: The type of agenda item you want to propose.
- [ ] Governance: New project

**Related working groups**:

- [ ] Open Source
- [ ] Oversight Committee

**Related issues or discussions**:

Please list all related issues so that we can see the originating conversation, e.g. #10 or https://github.com/Green-Software-Foundation/discussions/discussions/5

**More information**:
> Any other information you want to add.

**Comment by tmcclell** [comment]
Proposal allow 2 project leads for CarbonQL. No objections - approved by OC.
