### ISSUE TITLE
[Agenda Item] Can we open up slack for everyone?

### ISSUE THREAD

**Issue by Willmish** [Green-Software-Foundation/oc#39]
**Overview**:
Most open source foundations/communities have widely available IRC, Discord servers/Slack servers that anyone can join and ask a question, open a discussion. If It is not done so already, can we openly share slack invite link, and add an invite link to slack here: https://greensoftware.foundation/join-us . Also maybe share it on the github page?

**Related topic**: The type of agenda item you want to propose.
- [ ] Governance: New project
- [ ] Governance: Other
- [ ] Process
- [x] External Engagement
- [ ] Technology
- [ ] Other

**Related working groups**:

- [x] Community
- [ ] Open Source
- [ ] Policy
- [ ] Standards
- [x] Oversight Committee

**Related issues or discussions**:

Please list all related issues so that we can see the originating conversation, e.g. #10 or https://github.com/Green-Software-Foundation/discussions/discussions/5

**More information**:
> Any other information you want to add.

**Comment by adamj89** [comment]
We are currently trialling having our discussions centralised on GitHub. It would be good to see how this plays out as many GSF members do not have Slack access at work.

**Comment by Willmish** [comment]
E.g. - Zephyr Project community has a public Slack anyone can join and is widely used for project involvment, onboarding etc (while Steering Committee meetings etc are run seperately on Teams/Zoom)

<img width="1474" alt="Screenshot 2023-07-11 at 18 23 28" src="https://github.com/Green-Software-Foundation/oc/assets/26546660/d6f7f038-dbf9-48e5-83f6-6cc24e73acc2">

**Comment by tmcclell** [comment]
Discussions around Slack for informal discussions and direct messaging. @seanmcilroy29 will review to see if we can have a channel for informal communications for DM and General Discussion? Discussion for consolidation of public channels for non-GSF members and keep private channels for internal GSF. Recommendation to resolve the non members proposal and return to the tooling.

**Comment by jawache** [comment]
This is an old issues and since the conversations have moved over to GitHub discussions: https://github.com/orgs/Green-Software-Foundation/discussions

Closing this issue since we have a lot open, re-open if there is more to discuss.
