### ISSUE TITLE
WG/Project 'Discussions' page Consolidation

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/oc#42]
Proposal to Consolidate all the WG/Project 'Discussion' pages into a single area - https://github.com/orgs/Green-Software-Foundation/discussions/categories/standards-working-group

**Comment by jawache** [comment]
@adamj89 I believe this is either in progress or complete, could you advise if we can close this ticket or is there more left to discuss via the OC?

**Comment by adamj89** [comment]
Still a couple of channels left but happy to close this
