### ISSUE TITLE
GSF Green Maturity Matrix for Tech

### ISSUE THREAD

**Issue by aecurrie** [Green-Software-Foundation/oc#46]
### The GSF Green Maturity Matrix
A green tech self assessment tool for organisations

This project is a spin off of the O'Reilly book "Building Green Software" https://learning.oreilly.com/library/view/building-green-software/9781098150617/ where Anne is getting contacts from consultants asking if there is a definitive maturity matrix they can point to. 

**What is it**
The green maturity matrix is a self-assessment tool. It helps organisations understand the extent to which they have implemented green principles, patterns, and processes for building and operating their software systems.

**Quotes**
_"The GSF's maturity matrix allowed us to understand how far we have come and what we need to do next. It has given impetus and focus to our energy transition project."_ - Nero Cortex, CTO of HighlyDubious.AI

_"The maturity matrix helped us explain to our new client the service we were offering and what green software systems would look like for them. That allowed us to persuade them to invest time and effort in the project, knowing they could assess progress and prove it wasn't greenwashing."_ - Gaia Greengoody, TwoShoes Technology Consulting 

**Audience**
The audience for the green maturity matrix is 
1) Enterprise CTOs and internal green advocates to guide their high-level journey and give them something to report progress against.
2) Consultants offering green transition services.

They both attend conferences such at the OReilly Superstream (where we are already presenting) QCON (where we are involved with the green tracks) and the associated publications. The GSF maturity matrix should be an attractive piece of content for those and also for analyst's reports.

They also read O Reilly books, and we would push the project via "Building Green Software".

**ToC**
A maturity matrix supports the knowledge pillar by pushing people towards training at the entry level and then towards the processes and principles and SCI as folk migrate to higher maturity (i.e. it is an onboarding and pipeline tool for the rest of the GSF offerings)

**Governance**: Which working group(s) do you think should govern this project?

- [X] Community
- [ ] Open Source
- [ ] Policy
- [ ] Standards

Although the project could run through standards it falls more naturally to community as it is a way to transition tech industry folk to the standards offerings. I.e. it is a way to grow the community and bridge to standards.

**Problem**: 
The Matrix addresses four problems. It answers the questions:
- "Where do I start?"
- "Where am I now?"
- "What am I heading towards?"
- "How do I know I am making progress?"

"Building Green Software" gives some context and background but it doesn't help measure progress. The SCI measures progress but it doesn't start from nowhere and it doesn't place incremental actions of improvement within the context of a larger strategy.

**Solution**
The solution is a simple maturity matrix with 5-6 levels of carbon efficiency and awareness in a poster-style diagram, together with a short guide. Training courses including those offered by the GSF, and standards such as the SCI & ISO can be overlaid. 

**Closure**: 
We measure project success through online references and material downloads. If it is successful, we can offer training courses or certification in the matrix.

**FAQ**:

**Comment by PindyBhullar** [comment]
I have also added a proposal to the discussion in https://github.com/Green-Software-Foundation/oc/discussions/18

**Comment by aecurrie** [comment]
Great.

**Comment by tmcclell** [comment]
Microsoft has a tool in place that does just this I believe - https://learn.microsoft.com/en-gb/assessments/f236012a-0070-45db-b94c-fe8de0799f38/. As an example - we use this as part of a value based delivery approach - assessment, education, and use case.

**Comment by tmcclell** [comment]
The CWG are confused about where the matrix is in it's development. Russ to have conversation with Anne - what is needed at this time CWG. Discuss at our next meeting.

**Comment by aecurrie** [comment]
At the moment there is a basic early draft document version that was
originally authored by me with considerable input and feedback from various
community members (it was originally intended for the O Reilly book,
Building Green Software). It isn't finished yet. I would like to get it
finished within the GSF (although happy to do the bulk of the work)

**Comment by Sealjay** [comment]
The matrix sounds good. As well as a poster, is it worth having just a checklist of actions to take?

**Comment by aecurrie** [comment]
Good idea

**Comment by russelltrow** [comment]
Project approved
