### ISSUE TITLE
2023-09-04 - Oversight Committee Agenda

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/oc#47]
## Agenda - 2023 09 04

Time 1630pm (BST) - See the time in your [timezone](https://everytimezone.com/s/99162c8e)

- Chair – Tammy McClellan @tmcclell (Microsoft)  
- Vice-Chair – Chris Lloyd-Jones @Sealjay (Avanade)
- Convener – Sean Mcilroy @seanmcilroy29  (GSF)

## Antitrust Policy
Joint Development Foundation meetings may involve participation by industry competitors, and it is the intention of the Joint Development Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

If you have questions about these matters, please contact your company counsel or counsel to the Joint Development Foundation, DLA Piper.

## Roll Call
Please add 'Attended' to this issue during the meeting to denote attendance.
Any untracked attendees will be added by the GSF team below:

## Agenda
- [ ] Review/Approve agenda

## Documentation reminder
- [ ] **[Oversight Committee Documentation](https://oc.greensoftware.foundation/)**

### Governance
- [ ] https://github.com/Green-Software-Foundation/oc/issues/23
- [ ] https://github.com/Green-Software-Foundation/oc/issues/49
- [ ] https://github.com/Green-Software-Foundation/oc/issues/26
- [ ] #50 
- [ ] https://github.com/Green-Software-Foundation/oc/issues/36

### Proposed new projects
- [x] #44  
- [ ] https://github.com/Green-Software-Foundation/oc/discussions/17 - Sarah @greenhsu123: 
AI: @jawache to revert on https://github.com/Green-Software-Foundation/oc/discussions/17 

### Agenda submissions
- [ ] #33 
- [ ] #32 
- [ ] #35

### Process Improvement
- [ ] Review the GSF Contributing Writers' Guidelines 
> Sean - sent via email asking for objections, with none received; can we remove this?
- [ ] #36
- [ ] #37

## Answering the so-what question
- [ ] https://github.com/Green-Software-Foundation/oc/discussions/18
- [ ] https://github.com/Green-Software-Foundation/oc/discussions/16 - Sarah

### Regular updates
- [ ] https://github.com/Green-Software-Foundation/oc/issues/29

## AOB
- [ ] Any questions or other business

## Next meeting
- [ ] 03rd Oct

## Adjourn
- [ ] Any objections?

**Comment by Henry-WattTime** [comment]
attended
