### ISSUE TITLE
[Agenda Item] Clarifying the project incubation approval process

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/oc#49]
**Overview**:
The project incubation approval process is confusing and has caused there to be lengthy delays in project approval. 

The original intention to bring project approval to the OC was because of some concerns raised that projects we're being approved in one WG however should have existed in another. We didn't add clarity so this evolved to a dual approval process where it's unclear who has the ultimate rights to approve a project. 

Since the OC meets monthly and sometimes meetings are cancelled, sometimes the agenda is long, a project can be approved by a WG and then wait months for OC approval and only then can people start working on it. Interest in working on some projects has fizzled out because of this.

The main function of the OC is around graduating projects. The WG's are best suited to decide if a project can be born, the OC is best suited to decide if a project deserves to graduate.

Adding this change to the language: https://github.com/Green-Software-Foundation/oc/pull/48

Summarize:
- Only WG's can approve.
- OC can comment/object.
- If no objections from OC 2 weeks post WG approval, the project is approved.

**Related topic**: The type of agenda item you want to propose.
- [x] Governance: New project
- [ ] Governance: Other
- [x] Process
- [ ] External Engagement
- [ ] Technology
- [ ] Other

**Related working groups**:

- [ ] Community
- [ ] Open Source
- [ ] Policy
- [ ] Standards
- [ ] Oversight Committee

**Related issues or discussions**:

Please list all related issues so that we can see the originating conversation, e.g. #10 or https://github.com/Green-Software-Foundation/discussions/discussions/5

**More information**:
> Any other information you want to add.

**Comment by russelltrow** [comment]
Change implemented
