### ISSUE TITLE
Graduation review for Carbon Aware SDK v1

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/oc#56]
# Context

In the [October OC meeting](https://github.com/Green-Software-Foundation/oc/issues/52) we agreed to start the project [graduation review](https://oc.greensoftware.foundation/project-lifecycle.html#incubation) process for the [Carbon Aware SDK](https://github.com/Green-Software-Foundation/carbon-aware-sdk).

# Criteria

* The OC has the information it needs about CASDK v1 to determine whether it merits moving to the Graduated stage.
* The OC has a clear set of criteria that it can used to make the decision in a fair and unbiased way.
* Graduation Reviews take place in monthly OC calls
* There is a suitable celebration arranged if/when the graduation is approved.

# Actions

- [x] Agree the [Incubation Exit Criteria](https://oc.greensoftware.foundation/project-incubation-exit.html) / https://github.com/Green-Software-Foundation/oc/issues/23
- [ ] Schedule the graduation review for December meeting

**Comment by Sophietn** [comment]
Pushing the graduation review back from December to January 2nd OC meeting (although we assume this could be async due to holiday period). 
We're doing this because we're focusing on Carbon Aware SDK v1.2 release 12th December. 
After that we'll prioritise additional documentation for Graduation v1.3 release.

**Comment by Sophietn** [comment]
**21st February update**
The Carbon Aware SDK team are now ready to commence the Lifecycle Stage change approval process. 
Evidence of the project's fulfilment of the Graduated Lifecycle Stage Acceptance criteria is documented in this issue. #79 
I will circulate this via the Oversight Committee email mailing list and raise a motion to approve there. 
cc Project Leads @vaughanknight @Willmish
