### ISSUE TITLE
[Agenda Item] Update to Software Project Lifecycle

### ISSUE THREAD

**Issue by Sophietn** [Green-Software-Foundation/oc#63]
## Overview
**Revised Software Project Lifecycle to be reviewed**

5 Stages:
1. **Proposal** - Any GSF Member may raise a project proposal idea. 
2. **Incubation** - The project is in it’s experimental stage, and is being explored by the project team.  
3. **Graduated** - The project is considered mature and stable, and is supported by an active community. 
4. **Maintained** - The project is considered Graduated but new versions aren’t being released, except for bug fix maintenance. 
5. **Archived** - The project is considered dormant and any releases are no longer being maintained. 

![image](https://github.com/Green-Software-Foundation/oc/assets/144015600/22853525-e97c-4198-92c8-77592c4e31a4)

**Revised Acceptance Criteria to Incubation (for awareness)**

- The proposed project must meet the following requirements to reach Incubation: 
- Have a representative of at least one GSF member company participating, who is a WG attendee who will champion the project, volunteer to run it as project lead and share updates at the WG
- Have an assigned GSF PM
- Project name should not be trademarked and should have the approval of GSF marketing
- Similar or competitive projects are allowed. Projects are not excluded for reasons of overlap. 

**Revised Acceptance Criteria to Graduate (to be reviewed)** 

The project must meet the Incubation requirements as well as the following:

- Have a active set of contributing members from at least two member organisations
- Have a public GitHub repo with clear project documentation on
  - Project overview (ReadMe)
  - How to contribute (contributing.md )
  - End User Guide (enablement.md)
  - Test coverage
  - Fit within GSF Theory of Change
- Have made a release deployment, even a ‘developer preview’
- Evidence of usefulness through real world use cases in the production environment, including testimonials (adopters.md)
- Have 100% of the applicable criteria for the Open SSF Best Practice Badge (security.md)
- Have an incident process agreed with GSF PM.
- Have GSF processes set up including
  - Project meetings and mailing lists
  - Up to date project documentation on confluence
  - Provide regular updates to the relevant WG
  - Have defined OKRs agreed by the GSF PM
- Similar or competitive projects are allowed, but the project should not contradict with another GSF Graduated project.

## Related topic

The type of agenda item you want to propose.
- [ ] Governance: New project
- [x] Governance: Other
- [x] Process
- [ ] External Engagement
- [ ] Technology
- [ ] Other

## Related working groups

- [ ] Community
- [ ] Open Source
- [ ] Policy
- [ ] Standards
- [x] Oversight Committee

## Related issues or discussions

Once agreed a PR will be raised to update [this page on the OC website ](https://oc.greensoftware.foundation/project-lifecycle.html)

Please list all related issues so that we can see the originating conversation, e.g. #10 or https://github.com/Green-Software-Foundation/discussions/discussions/5

**More information**:
> Any other information you want to add.

**Comment by tmcclell** [comment]
Love the proposal and detail outlines. Can't think of anything to add at this time. Good work @Sophietn!

**Comment by Sophietn** [comment]
Thanks @tmcclell! 
The PR to update the OC website with these changes is here: https://github.com/Green-Software-Foundation/oc/pull/64
I'll merge tomorrow if no objections.

**Comment by Sophietn** [comment]
[PR](https://github.com/Green-Software-Foundation/oc/pull/64) raised. 
9th Nov Motion raised. 5 days notice given. 2 approvals received and no objections. 
14th Nov merged.
Closing this issue
