### ISSUE TITLE
2023-12-05 - Oversight Committee Agenda

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/oc#65]
## Agenda - 2023-12-05

Time 16:30 (UTC) - See the time in your [timezone](https://everytimezone.com/s/5c485561)

- Chair – Tammy McClellan (Microsoft)  
- Vice-Chair – Chris Lloyd-Jones (Avanade)
- Convener – Russ Trow (GSF)

## Antitrust Policy
Joint Development Foundation meetings may involve participation by industry competitors, and it is the intention of the Joint Development Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

If you have questions about these matters, please contact your company counsel or counsel to the Joint Development Foundation, DLA Piper.

## Roll Call
Please add 'Attended' to this issue during the meeting to denote attendance.
Any untracked attendees will be added by the GSF team below:

## Agenda
- [ ] Convene & Roll Call
- [ ] Review previous meeting: https://github.com/Green-Software-Foundation/oc/issues/52
- [ ] Review/Approve agenda

## Projects

[**GSF Project Tracker**](https://airtable.com/appVPOiFrCIjAAcvB/shrNADml6TRL1bm4j)

- [ ] https://github.com/Green-Software-Foundation/oc/issues/56 - In progress

## Governance

- [ ] https://github.com/Green-Software-Foundation/oc/issues/50
- [ ] https://github.com/Green-Software-Foundation/oc/issues/37
- [ ] Request for Discussion: Async-First Working Groups & OC

## AOB
- [x] Reschedule or Cancel next meeting?

## Next meeting
- [ ] 2nd January 2024

## Adjourn
- [ ] Any objections?

**Comment by russelltrow** [comment]
Attended

**Comment by srini1978** [comment]
Attended

**Comment by Sealjay** [comment]
Attended!

**Comment by Henry-WattTime** [comment]
Attended

**Comment by russelltrow** [comment]
# Meeting Notes

## Projects

* Project Tracker is blocked for Avanade as it's not had a security review - Could the information be shared in another way? (@adamj89)

- [ ] @russelltrow @Sophietn @seanmcilroy29 update Chairs/Leads on the GSF Project Tracker

### Graduation review for Carbon Aware SDK v1

* Discussed the graduation review for CASDK. Confirmed that they are aiming for Graduation in Jan after release 1.2
* Briefly discussed the revised graduation criteria: https://oc.greensoftware.foundation/project-lifecycle.html#graduated

- [ ] @Sophietn provide OC with further details on the Graduation Review process and the criteria ahead of the actual activity

## Elections

https://greensoftwarefoundation.atlassian.net/wiki/spaces/~612dd45e45cd76006a84071a/pages/93814822/Elections

* Google Docs is blocked for a number of people including @greenhsu123. Thought we agreed to a different approach? (@seanmcilroy29)

- [ ] @seanmcilroy29 update the "Current Working Group Chairs" section with WG names
- [ ] @seanmcilroy29 ensure the nomination submissions are correct - e.g. Tammy hasn't applied for CWG
- [ ] @seanmcilroy29 provide a status update on the elections this week

## Individual Contributors

* @Sealjay asked about the status of ICs.
* @jawache discussed the legal challenges of having ICs.
* Suggestion of creating a new level such as Affiliate or Observer and having a 
* Suggestion of making all meetings public and having a blanket disclaimer covering all contributions
* Will need to be discussed at the Steering Committee

## Async-First

* @russelltrow @jawache verbally shared their idea on moving Working Groups to an 'async-first' approach
* Discussed increased use of email for communication - "Tammy already has 100+ emails a week"
* Agreed that a cultural change is required not just different tooling
* Discussed new Member Onboarding - Buddy system was trialed in the Standards WG, not a huge uptake

- [ ] @russelltrow to share an RFD with the group
- [ ] @russelltrow find examples of other organisations who successfully run 'async-first'
- [ ] @jawache @NAMRATA-WOKE investigate the Buddy system trialed in the Standards WG

# Actions

- [ ] @russelltrow ask group if they wish to cancel or reschedule January 2nd meeting
