### ISSUE TITLE
Decision on January 2024 meeting

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/oc#67]
Our next OC meeting is scheduled for Tuesday 2nd January. As this is so close to New Year would the group like to:

- [ ] Reschedule to Tuesday 9th January
- [x] Cancel the meeting
- [ ] Leave on 2nd January

Please let me know your thoughts. Unless I hear otherwise the meeting will go ahead on 2nd January.

**Comment by russelltrow** [comment]
@tmcclell @Sealjay do you have any preferences?

**Comment by tmcclell** [comment]
I'll be traveling that day for a customer, so I vote to cancel January 2nd.

**Comment by russelltrow** [comment]
Meeting cancelled
