### ISSUE TITLE
Publish this repo on the web

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/oc#8]
**What**: Publish this website at oc.greensoftware.foundation
**Why**: So this groups rules and policies can be easily shared with other members in the Foundation.
**Success**: A website with the current contents at oc.greensoftware.foundation, anytime main branch is commited to the website updates.

Note this repo uses the same logic as https://toc.hyperledger.org/ to build and run the website, just github pages and jeckll theme.

**Comment by osamajandali** [comment]
@jawache Please edit the DNS for oc.greensoftware.foundation to work with github pages

**Comment by osamajandali** [comment]
@jawache Also, I've tried to customize the colors but this template have issue I can do much to that purple color

**Comment by zanete** [comment]
@jawache to give @osamajandali access so he can do himself

**Comment by osamajandali** [comment]
Done!

**Comment by zanete** [comment]
Great, I see things when i visit https://oc.greensoftware.foundation/
